namespace Noir.Autogenerated {
    using System.Collections.Generic;
    public class Scenes{
    // This class is auto-generated do not modify. (Build by CodeGenerator.cs)
    // Last Generated: 3/23/2025 7:41:24 AM
    // Content hash: 9311D3C5F9D1D800C18C5ED568179BF9E15B93C1750A5E80339253911F49F827
				public const string SAMPLESCENE = "SampleScene";

		public static List<string> All = new List<string>() {
			"SampleScene",
		};

    }
}