namespace Noir.Autogenerated {
    using System.Collections.Generic;
    public class Tags{
    // This class is auto-generated do not modify. (Build by CodeGenerator.cs)
    // Last Generated: 3/23/2025 7:41:24 AM
    // Content hash: 52BB564DC4B008E8F0131A77DD13B6FC86E39320A3C5DA53280446AEE2A29686
				public const string UNTAGGED = "Untagged";

				public const string RESPAWN = "Respawn";

				public const string FINISH = "Finish";

				public const string EDITORONLY = "EditorOnly";

				public const string MAINCAMERA = "MainCamera";

				public const string PLAYER = "Player";

				public const string GAMECONTROLLER = "GameController";

		public static List<string> All = new List<string>() {
			"Untagged",
			"Respawn",
			"Finish",
			"EditorOnly",
			"MainCamera",
			"Player",
			"GameController",
		};

    }
}