site_name: Noir Library Documentation
theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.escapeall:
      hardbreak: true
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
