site_name: Noir Library Documentation
site_author: Trouble Cat Studios
site_description: >-
  A library designed to make game development in Unity easier.

# Repository
repo_name: troublecatstudios/noir
repo_url: https://github.com/troublecatstudios/noir

site_url: 'https://troublecat.io/noir/'

# Copyright
copyright: Copyright &copy; 2024 - 2025 Trouble Cat Studios

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/troublecatgames
    - icon: fontawesome/brands/github
      link: https://github.com/troublecatstudios

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: troublecat
  features:
    - search.highlight
    - search.suggest
    - navigation.top
    - navigation.sections
    - navigation.tabs
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - toc.follow
  font:
    text: Noto Sans
    code: Anonymous Pro
hooks:
  - docs/hooks/tc_shortcodes.py
plugins:
  - search
  - include_dir_to_nav
  - git-revision-date-localized:
      enabled: !ENV [GITHUB_ACTIONS, false]
      enable_creation_date: true
      type: timeago
  - git-committers:
      enabled: !ENV [GITHUB_ACTIONS, false]
      repository: troublecatstudios/noir
      branch: develop
      exclude:
        - reference/**
markdown_extensions:
  - admonition
  - attr_list
  - callouts
  - def_list
  - footnotes
  - github-callouts
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      title: On this page
      permalink: true
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
extra_css:
  - stylesheets/troublecat.css
nav:
  - Home: README.md
  - Getting started:
      - Installation: getting_started/installing.md
      - License: getting_started/license.md
      - Changelog: getting_started/changelog.md
      - Third party libraries: getting_started/third_party.md
  - Features:
      - features/index.md
      - Gameplay:
        - features/procedural_generation.md
      - Editor:
        - features/variables.md
        - features/attributes.md
  - Contributing:
      - contributing/developing.md
      - Building: contributing/building.md
      - Development tasks: contributing/development_tasks.md
  - Reference:
      - reference/README.md
      - reference/conventions.md
      - Noir: reference/Noir
      - NoirEditor: reference/NoirEditor
  - Tutorials:
      - tutorials/README.md
      - Automatic ScriptableObjects: tutorials/automatic-scriptableobject-creation.md
      - Included samples: tutorials/samples.md
