using System;

namespace NoirEditor.CodeGen {
    public class CodeGenTask {
        public string CodeNamespace { get; set; } = "Noir.Autogenerated";
        public string FileExtension { get; set; } = ".cs";
        public string CodeClassName { get; set; } = string.Empty;
        public Func<string> ContentBuilder { get; set; } = () => string.Empty;
        public Func<string> HashTargetBuilder { get; set; } = () => string.Empty;
        public string[] ImportNamespaces { get; set; } = Array.Empty<string>();
    }
}