using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Noir.Logging;

namespace NoirEditor.CodeGen {
    public class CodeGenerator {
        private readonly string _outputFolder;

        private readonly List<CodeGenTask> _tasks = new();

        public CodeGenerator(string outputFolder = "TroubleCatStudios/Noir.Autogenerated/") {
            if (outputFolder.StartsWith("/")) {
                outputFolder = outputFolder.Substring(1);
            }
            if (!outputFolder.EndsWith("/")) {
                outputFolder += "/";
            }
            _outputFolder = outputFolder;
        }

        public void AddTask(CodeGenTask task) => _tasks.Add(task);
        public void AddTasks(IEnumerable<CodeGenTask> tasks) => _tasks.AddRange(tasks);

        public CodeGenReport Generate(bool force = false, bool dryRun = false) {
            AssetDB.Mkdirp(_outputFolder);

            var startTime = DateTime.Now;
            var results = new List<(string FileName, string Hash)>();
            foreach (var task in _tasks) {
                var codeContents = task.ContentBuilder();
                var hashTarget = task.HashTargetBuilder();
                var hash = GetHashString(hashTarget);
                var outputFile = "Assets/" + _outputFolder + task.CodeClassName + task.FileExtension;
                var previousHash = CodeGenFile.GetHashFromSourceFile(outputFile);
                var shouldWrite = force || hash != previousHash;
                if (shouldWrite) {
                    var contents = CodeGenFile.GetClassWrapper(task.CodeNamespace, task.CodeClassName, GetFileHeader(hash) + codeContents, task.ImportNamespaces);
                    if (!dryRun) {
                        File.WriteAllText(outputFile, contents);
                    }
                }
                LoggerSingleton.Debug<CodeGenerator>($"Task fileName={task.CodeClassName}, filePath={outputFile}, namespace={task.CodeNamespace}, hash={hash}, previousHash={previousHash}, shouldWrite={shouldWrite}");
            }
            return new CodeGenReport() {
                StartTime = startTime,
                TimeTaken = TimeSpan.FromTicks(DateTime.Now.Ticks - startTime.Ticks),
                GeneratedFiles = results.ToArray(),
            };
        }

        private static string GetFileHeader(string hash) {
            var output = "";
            output += $"    // This class is auto-generated do not modify. (Build by {nameof(CodeGenerator)}.cs)\n";
            output += $"    // Last Generated: {DateTime.Now}\n";
            output += $"    // Content hash: {hash}\n";
            return output;
        }

        private static byte[] GetHash(string inputString) {
            using HashAlgorithm algorithm = SHA256.Create();
            return algorithm.ComputeHash(Encoding.UTF8.GetBytes(inputString));
        }

        private static string GetHashString(string inputString) {
            var sb = new StringBuilder();
            foreach (byte b in GetHash(inputString.Replace("\n", string.Empty).Replace("\r\n", string.Empty)))
                sb.Append(b.ToString("X2"));

            return sb.ToString();
        }
    }
}