#if !NOIR_CODE_GEN_DISABLED
// This class is auto-generated do not modify. (Build by CodeGenerator.cs)
// Last Generated: 4/7/2025 7:49:27 AM
// Content hash: E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855

namespace Noir.Autogenerated {
    using System.Collections.Generic;
    using Noir;
    using Noir.DataObjects;
    using Noir.Variables;
    using System;
    using UnityEngine;
    public class Variables{



		/// <summary>Gets a variable by name.</summary>
		public static T GetByName<T>(string key) where T : DataVariable {
		    var variable = NoirDataLibrary.Instance.GetVariableByName<T>(key);
		    return variable;
		}

		public static class Names {
				public static List<string> All = new List<string>() {
				};
		}

    }
}

#endif