namespace Noir.Autogenerated {
    using System.Collections.Generic;
    public class Layers{
    // This class is auto-generated do not modify. (Build by CodeGenerator.cs)
    // Last Generated: 3/23/2025 7:41:24 AM
    // Content hash: 62584A87F69B65DCD66D198D332C91C503903254DBBA4D6618F92CD980BE129F
				public const string DEFAULT = "Default";

				public const string TRANSPARENTFX = "TransparentFX";

				public const string IGNORERAYCAST = "Ignore Raycast";

				public const string WATER = "Water";

				public const string UI = "UI";


		public const int DEFAULT_INT = 0;
		public const int TRANSPARENTFX_INT = 1;
		public const int IGNORERAYCAST_INT = 2;
		public const int WATER_INT = 4;
		public const int UI_INT = 5;
		public static Dictionary<int, string> All = new Dictionary<int, string>() {
			{  0 ,"Default" },
			{  1 ,"TransparentFX" },
			{  2 ,"Ignore Raycast" },
			{  4 ,"Water" },
			{  5 ,"UI" },
		};

    }
}