namespace Noir.Autogenerated {
    using System.Collections.Generic;
    public class SortingLayers{
    // This class is auto-generated do not modify. (Build by CodeGenerator.cs)
    // Last Generated: 3/23/2025 7:41:24 AM
    // Content hash: 798F76590A5EA80F187411F89A5C1A2C7A9553DF8E25D22F01F0BD6796A45A46

		public const string DEFAULT = "Default";

		public const int DEFAULT_INT = 0;

		public static Dictionary<int, string> All = new Dictionary<int, string>() {
			{ 0, "Default" },
		};

    }
}