name: Release Automation

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Release Type
        options:
        - major
        - minor
        - patch

  push:
    branches:
    - stable

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    # Retrieve the merged PR information
    # -----------------------------
    - uses: actions-ecosystem/action-get-merged-pull-request@v1
      id: get-merged-pull-request
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # Determine the kind of release to create
    # -----------------------------
    # note: this uses the release/* labels on the merged PR
    # so if no PR was merged then this step won't run.
    - uses: actions-ecosystem/action-release-label@v1
      id: release-label
      if: ${{ steps.get-merged-pull-request.outputs.title != null }}
      with:
        labels: ${{ steps.get-merged-pull-request.outputs.labels }}

    # Get the latest semver tag as our "source version"
    # -----------------------------
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      with:
        semver_only: true

    # Exit the workflow if there's no release type
    # -----------------------------
    - uses: actions/github-script@v7
      id: check
      if: steps.release-label.outputs.level == null && github.event.inputs.release_type == null
      with:
        script: |
          const { owner, repo } = context.repo
          console.log('Cancelling ...');
          const run_id = "${{ github.run_id }}";
          await github.rest.actions.cancelWorkflowRun({ owner, repo, run_id });
          return 'stop'
        result-encoding: string
    - name: Waiting for cancellation
      if: steps.release-label.outputs.level == null && github.event.inputs.release_type == null
      run: sleep 60

    # Increment the version according to the semver release type
    # -----------------------------
    # note: this uses either the release type from the actions-ecosystem/action-release-label
    # step or the type chosen in the workflow_dispatch
    - uses: ./.github/actions/version
      id: versioning
      if: steps.release-label.outputs.level != null || github.event.inputs.release_type != null
      with:
        release_type: ${{ steps.release-label.outputs.level && steps.release-label.outputs.level || github.event.inputs.release_type }}


    # Update the changelog
    # -----------------------------
    - uses: ./.github/actions/changloe
      id: changelog
      if: steps.release-label.outputs.level != null || github.event.inputs.release_type != null
      with:
        version: ${{ steps.versioning.outputs.new_version }}

    # Push version tag
    # -----------------------------
    - uses: actions-ecosystem/action-push-tag@v1
      if: ${{ steps.versioning.outputs.new_version != null }}
      with:
        tag: ${{ steps.versioning.outputs.new_version }}
        message: "${{ steps.versioning.outputs.new_version }}: PR #${{ steps.get-merged-pull-request.outputs.number }} ${{ steps.get-merged-pull-request.outputs.title }}"

    # Create GitHub Release
    # -----------------------------
    - uses: actions/create-release@v1
      if: ${{ steps.versioning.outputs.new_version != null }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.versioning.outputs.new_version }}
        release_name: v${{ steps.versioning.outputs.new_version }}
        body: ${{ steps.changelog.outputs.content }}

    # Create/Update the upm branch
    # -----------------------------
    - name: update upm branch
      if: ${{ steps.versioning.outputs.new_version != null }}
      shell: bash
      run: |
        git subtree split -P "./package" -b upm
        git push -u origin upm

    # Post comment back to PR with release information
    # -----------------------------
    - uses: actions-ecosystem/action-create-comment@v1
      if: ${{ steps.get-merged-pull-request.outputs.title != null }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.get-merged-pull-request.outputs.number }}
        body: |
          The new version [${{ steps.versioning.outputs.new_version }}](https://github.com/${{ github.repository }}/releases/tag/${{ steps.versioning.outputs.new_version }}) has been released
