name: Build Projects

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - stable
    paths:
      - package/Editor/**
      - package/Runtime/**
      - .github/workflows/build.yaml
      - .github/build/**
      - unity-project/**

permissions:
  contents: write

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/.build/nuget
  CRANKY_MIN_COVERAGE: 50
  CRANKY_ACCEPTABLE_COVERAGE: 85

jobs:
  #
  # Prep
  # --------------------------------------------------------------------------------
  # prep does the following work so that the other jobs can execute successfully.
  #
  # - Determine the unity version currently used in unity-project/
  #
  prep:
    runs-on: ubuntu-latest
    outputs:
      unity_version: ${{ steps.unity-get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: akiojin/unity-get-version-github-action@v1.1.4
        id: unity-get-version
        with:
          project-directory: ./unity-project
  #
  # Build
  # --------------------------------------------------------------------------------
  # build handles building the project libraries via dotnet and uploads the output
  # via actions/upload-artifact so that it can be used by later jobs
  #
  build:
    runs-on: ubuntu-latest
    needs: [ prep ]
    container:
      image: unityci/editor:ubuntu-${{ needs.prep.outputs.unity_version }}-base-3.1.0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Nerdbank.GitVersioning requires a full clone to correctly calculate the version height
      - name: Mark repository as safe
        shell: bash
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: .github/build/global.json
      - name: Build code and create NuGet packages
        shell: bash
        run: |
          cd ./.github/build
          dotnet build ./Noir.csproj
          dotnet build ./NoirEditor.csproj
          dotnet pack --configuration Release Noir.csproj
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}-${{ github.run_number }}
          if-no-files-found: error
          include-hidden-files: true
          path: .build/
      - uses: actions/upload-artifact@v4
        with:
          name: nuget-${{ github.sha }}-${{ github.run_number }}
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/**/*.nupkg

  #
  # Test
  # --------------------------------------------------------------------------------
  # test handles running the playmode and editmode tests within Unity. This is done
  # via the game-ci/unity-test-runner action
  #
  test:
    runs-on: ubuntu-latest
    needs: [ prep ]
    permissions:
      contents: write
      issues: write
      checks: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.FOSS_UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.FOSS_UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.FOSS_UNITY_PASSWORD }}
        with:
          projectPath: unity-project
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: ${{ needs.prep.outputs.unity_version }}

  #
  # API Docs Coverage
  # --------------------------------------------------------------------------------
  # this check verifies that the publicly accessible classes and members within our
  # libraries have documentation comments added to them.
  #
  api_docs_coverage:
    runs-on: ubuntu-latest
    needs: [prep]
    container:
      image: unityci/editor:ubuntu-${{ needs.prep.outputs.unity_version }}-base-3.1.0
    strategy:
      fail-fast: false
      matrix:
        project: ['Noir', 'NoirEditor']
    permissions:
      checks: write
      statuses: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Mark repository as safe
      shell: bash
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: .github/build/global.json
    - name: Build ${{ matrix.project }}.csproj
      shell: bash
      run: |
        cd ./.github/build
        dotnet build ./${{ matrix.project }}.csproj
    - name: Run Cranky
      id: cranky
      shell: bash
      run: |
        dotnet tool update cranky -g
        export PATH="$PATH:/github/home/.dotnet/tools"
        cranky --project .github/build/${{ matrix.project }}.csproj --github --set-exit-code --percentages ${{ env.CRANKY_MIN_COVERAGE }},${{ env.CRANKY_ACCEPTABLE_COVERAGE }}
    - uses: mshick/add-pr-comment@v2
      if: failure()
      with:
        message-id: api_doc_cov-${{ matrix.project }}
        message: |
          > [!CAUTION]
          > ${{ steps.cranky.outputs.health }} The public API documentation coverage for ${{ matrix.project }} (${{ steps.cranky.outputs.percent }}%) is below the minimum threshold of ${{ env.CRANKY_MIN_COVERAGE }}%

          **Documented API Members**: ${{ steps.cranky.outputs.documented }}
          **Undocumented API Members**: ${{ steps.cranky.outputs.undocumented }}

          <details>
          <summary>Raw output from <a href="https://github.com/ricardoboss/cranky" target="_blank">cranky</a></summary>

          ```plaintext
            Documentation coverage: ${{ steps.cranky.outputs.percent }} % (${{ steps.cranky.outputs.documented }}/${{ steps.cranky.outputs.total }})
            ${{ steps.cranky.outputs.message }}
          ```
          </details>

    - uses: mshick/add-pr-comment@v2
      if: success()
      with:
        message-id: api_doc_cov-${{ matrix.project }}
        message: |
          > [!NOTE]
          > ${{ steps.cranky.outputs.health }} The public API documentation coverage for ${{ matrix.project }} (${{ steps.cranky.outputs.percent }}%) is above the minimum threshold of ${{ env.CRANKY_MIN_COVERAGE }}%

          **Documented API Members**: ${{ steps.cranky.outputs.documented }}
          **Undocumented API Members**: ${{ steps.cranky.outputs.undocumented }}

          <details>
          <summary>Raw output from <a href="https://github.com/ricardoboss/cranky" target="_blank">cranky</a></summary>

          ```plaintext
            Documentation coverage: ${{ steps.cranky.outputs.percent }} % (${{ steps.cranky.outputs.documented }}/${{ steps.cranky.outputs.total }})
            ${{ steps.cranky.outputs.message }}
          ```
          </details>




  # Deploy NuGet
  # --------------------------------------------------------------------------------
  # publishes any generated *.nupkg files to the Trouble Cat Studios GitHub account
  #
  deploy_nuget:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      packages: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nuget-${{ github.sha }}-${{ github.run_number }}
          path: ${{ env.NuGetDirectory }}
      - uses: actions/setup-dotnet@v4
      - name: Publish NuGet packages
        shell: pwsh
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --source https://nuget.pkg.github.com/troublecatstudios/index.json --api-key "${{ secrets.GITHUB_TOKEN }}"
          }

  # Docs
  # --------------------------------------------------------------------------------
  # docs automatically updates the api documentation using the build outputs. If any
  # documentation has been changed, the results will be committed to the pull request
  # so documentation updates can be reviewed alongside the code changes.
  #
  docs:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4
        with:
          # we need to checkout the ref so we're not in a detached head state
          # when we go to make new commits to the repository
          ref: ${{ github.head_ref }}
      - name: Mark repository as safe
        shell: bash
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: .github/build/global.json
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-${{ github.sha }}-${{ github.run_number }}
          path: .build/
      - name: Output full repository structure
        shell: bash
        run: ls -lasR
      - name: Run dotnet2md to generate updated docs
        shell: bash
        run: |
          cd ./.github/scripts
          dotnet ./dotnet2md/dotnet2md.dll --source=./../../.build/bin/NoirEditor/Release/netcoreapp3.1/ --output=./../../docs/reference/ --reference-link-style=Directories Noir NoirEditor
      - name: Check for git changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
              echo "changes=true" >> "$GITHUB_OUTPUT";
          fi
      - name: Configure git credentials
        if: steps.check_changes.outputs.changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Commit documentation updates
        if: steps.check_changes.outputs.changes
        run: |
          git add -A
          git commit -m 'auto(docs): updates documentation'
          git push
