name: Update Documentation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - name: Build Code and Generate Markdown Documentation
        run: ./.github/scripts/gen-docs.sh
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
              echo "changes=true" >> "$GITHUB_OUTPUT";
          fi
      - name: Configure Git Credentials
        if: steps.check_changes.outputs.changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Commit Documentation Updates
        if: steps.check_changes.outputs.changes
        run: |
          git add -A
          git commit -m 'docs: updates documentation'
          git push
